"""Add delete-orphan to relations

Revision ID: 056345b0b5b7
Revises: b0521cf7ac6b
Create Date: 2024-12-02 02:07:03.806138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056345b0b5b7'
down_revision: Union[str, None] = 'b0521cf7ac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
