"""Add single-parent into GroupHierarchy table [child_group]

Revision ID: 1fbf5d574036
Revises: 4ec0aba048a9
Create Date: 2024-12-02 08:01:15.348426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbf5d574036'
down_revision: Union[str, None] = '4ec0aba048a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
