"""Add event_type enum in UserEvent table

Revision ID: 2366086a8b7a
Revises: 70a4cb944648
Create Date: 2024-11-30 09:14:29.275699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2366086a8b7a'
down_revision: Union[str, None] = '70a4cb944648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.Enum('personal', 'group', 'hierarchical', name='event_type'), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=True))
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
