"""Add group_id to UserEvent Table

Revision ID: 4334de7ff72f
Revises: 8b7ae802c594
Create Date: 2024-12-01 00:24:36.717241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4334de7ff72f'
down_revision: Union[str, None] = '8b7ae802c594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_user_event_group', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_event_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
