"""Add single-parent into GroupHierarchy table

Revision ID: 4ec0aba048a9
Revises: 056345b0b5b7
Create Date: 2024-12-02 07:59:44.231267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec0aba048a9'
down_revision: Union[str, None] = '056345b0b5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
