"""Add status enum in UserEvent table

Revision ID: 70a4cb944648
Revises: ea1c0fe3f4e7
Create Date: 2024-11-30 08:43:09.097998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a4cb944648'
down_revision: Union[str, None] = 'ea1c0fe3f4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='eventstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
