"""Columns modification in Notification table

Revision ID: 8b7ae802c594
Revises: bda7d32046c7
Create Date: 2024-11-30 19:26:00.282644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7ae802c594'
down_revision: Union[str, None] = 'bda7d32046c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.alter_column('event',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('is_read')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
