"""Add group to Notification Table

Revision ID: b0521cf7ac6b
Revises: c5cf83609daf
Create Date: 2024-12-01 18:44:03.743473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0521cf7ac6b'
down_revision: Union[str, None] = 'c5cf83609daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
