"""Change enum in UserEvent table

Revision ID: ea1c0fe3f4e7
Revises: 656dd3471023
Create Date: 2024-11-29 23:17:22.191747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1c0fe3f4e7'
down_revision: Union[str, None] = '656dd3471023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
